// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgg9PreACfZDzQaErNZGPov_HK0BFiPU',
    appId: '1:769602086043:web:574f071bfe737ce129923e',
    messagingSenderId: '769602086043',
    projectId: 'pushnotifications-746a4',
    authDomain: 'pushnotifications-746a4.firebaseapp.com',
    storageBucket: 'pushnotifications-746a4.appspot.com',
    measurementId: 'G-WCM55F87CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeI35r-MrWLSx5tev3rj5aIatZOCBxI7I',
    appId: '1:769602086043:android:c82f5f5cd449d1f229923e',
    messagingSenderId: '769602086043',
    projectId: 'pushnotifications-746a4',
    storageBucket: 'pushnotifications-746a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_uMNp5KQ9SERlBGj4dyUQUcIgufdqRs',
    appId: '1:769602086043:ios:20624c4a356e51e729923e',
    messagingSenderId: '769602086043',
    projectId: 'pushnotifications-746a4',
    storageBucket: 'pushnotifications-746a4.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX_uMNp5KQ9SERlBGj4dyUQUcIgufdqRs',
    appId: '1:769602086043:ios:8f2caa857d16067329923e',
    messagingSenderId: '769602086043',
    projectId: 'pushnotifications-746a4',
    storageBucket: 'pushnotifications-746a4.appspot.com',
    iosBundleId: 'com.example.delivery.RunnerTests',
  );
}
